//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace XPressMe.Data.XPressMeDemoDB
{

	 public partial class XPOGroup : XPOBaseItem
	 {
		  string fTitle;
		  [Size(50)]
		  public string Title
		  {
				get { return fTitle; }
				set { SetPropertyValue<string>("Title", ref fTitle, value); }
		  }
		  [Association(@"XPOPostReferencesXPOGroup", typeof(XPOPost))]
		  public XPCollection<XPOPost> Posts { get { return GetCollection<XPOPost>("Posts"); } }
	 }

}
