//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace XPressMe.Data.XPressMeDemoDB
{

	 public partial class XPOTag : XPOBaseItem
	 {
		  string fName;
		  [Size(50)]
		  public string Name
		  {
				get { return fName; }
				set { SetPropertyValue<string>("Name", ref fName, value); }
		  }
		  [PersistentAlias("Posts[Active== true].Count")]
		  public int PostCount
		  {
				get { return (int)(EvaluateAlias("PostCount")); }
		  }
		  [Association(@"XPOPostReferencesXPOTag", typeof(XPOPost))]
		  public XPCollection<XPOPost> Posts { get { return GetCollection<XPOPost>("Posts"); } }
	 }

}
